install.packages("devtools")
require(devtools)
install_github("braverock/FinancialInstrument")
install_github("braverock/blotter" , force = TRUE)
install_github("braverock/quantstrat")
install_github("braverock/PerformanceAnalytics")
install.packages('quantmod')
install.packages('TTR')
library(blotter)
